import = [
  "~/.config/alacritty/keymaps.toml",
  "~/.config/alacritty/theme.toml"
]
live_config_reload = true

[window]
opacity = 0.95
dynamic_padding = true
decorations = "none"
startup_mode = "Maximized"

[font]
size = 26.0

  [font.normal]
  family = "Hack Nerd Font Mono"

  [font.bold]
  family = "Hack Nerd Font Mono"

  [font.italic]
  family = "Hack Nerd Font Mono"

  [font.bold_italic]
  family = "Hack Nerd Font Mono"

[mouse]
hide_when_typing = true
