[[key_bindings]]
key = "A"
mods = "Alt"
chars = "\u001ba"

[[key_bindings]]
key = "B"
mods = "Alt"
chars = "\u001bb"

[[key_bindings]]
key = "C"
mods = "Alt"
chars = "\u001bc"

[[key_bindings]]
key = "D"
mods = "Alt"
chars = "\u001bd"

[[key_bindings]]
key = "E"
mods = "Alt"
chars = "\u001be"

[[key_bindings]]
key = "F"
mods = "Alt"
chars = "\u001bf"

[[key_bindings]]
key = "G"
mods = "Alt"
chars = "\u001bg"

[[key_bindings]]
key = "H"
mods = "Alt"
chars = "\u001bh"

[[key_bindings]]
key = "I"
mods = "Alt"
chars = "\u001bi"

[[key_bindings]]
key = "J"
mods = "Alt"
chars = "\u001bj"

[[key_bindings]]
key = "K"
mods = "Alt"
chars = "\u001bk"

[[key_bindings]]
key = "L"
mods = "Alt"
chars = "\u001bl"

[[key_bindings]]
key = "M"
mods = "Alt"
chars = "\u001bm"

[[key_bindings]]
key = "N"
mods = "Alt"
chars = "\u001bn"

[[key_bindings]]
key = "O"
mods = "Alt"
chars = "\u001bo"

[[key_bindings]]
key = "P"
mods = "Alt"
chars = "\u001bp"

[[key_bindings]]
key = "Q"
mods = "Alt"
chars = "\u001bq"

[[key_bindings]]
key = "R"
mods = "Alt"
chars = "\u001br"

[[key_bindings]]
key = "S"
mods = "Alt"
chars = "\u001bs"

[[key_bindings]]
key = "T"
mods = "Alt"
chars = "\u001bt"

[[key_bindings]]
key = "U"
mods = "Alt"
chars = "\u001bu"

[[key_bindings]]
key = "V"
mods = "Alt"
chars = "\u001bv"

[[key_bindings]]
key = "W"
mods = "Alt"
chars = "\u001bw"

[[key_bindings]]
key = "X"
mods = "Alt"
chars = "\u001bx"

[[key_bindings]]
key = "Y"
mods = "Alt"
chars = "\u001by"

[[key_bindings]]
key = "Z"
mods = "Alt"
chars = "\u001bz"

[[key_bindings]]
key = "A"
mods = "Alt|Shift"
chars = "\u001bA"

[[key_bindings]]
key = "B"
mods = "Alt|Shift"
chars = "\u001bB"

[[key_bindings]]
key = "C"
mods = "Alt|Shift"
chars = "\u001bC"

[[key_bindings]]
key = "D"
mods = "Alt|Shift"
chars = "\u001bD"

[[key_bindings]]
key = "E"
mods = "Alt|Shift"
chars = "\u001bE"

[[key_bindings]]
key = "F"
mods = "Alt|Shift"
chars = "\u001bF"

[[key_bindings]]
key = "G"
mods = "Alt|Shift"
chars = "\u001bG"

[[key_bindings]]
key = "H"
mods = "Alt|Shift"
chars = "\u001bH"

[[key_bindings]]
key = "I"
mods = "Alt|Shift"
chars = "\u001bI"

[[key_bindings]]
key = "J"
mods = "Alt|Shift"
chars = "\u001bJ"

[[key_bindings]]
key = "K"
mods = "Alt|Shift"
chars = "\u001bK"

[[key_bindings]]
key = "L"
mods = "Alt|Shift"
chars = "\u001bL"

[[key_bindings]]
key = "M"
mods = "Alt|Shift"
chars = "\u001bM"

[[key_bindings]]
key = "N"
mods = "Alt|Shift"
chars = "\u001bN"

[[key_bindings]]
key = "O"
mods = "Alt|Shift"
chars = "\u001bO"

[[key_bindings]]
key = "P"
mods = "Alt|Shift"
chars = "\u001bP"

[[key_bindings]]
key = "Q"
mods = "Alt|Shift"
chars = "\u001bQ"

[[key_bindings]]
key = "R"
mods = "Alt|Shift"
chars = "\u001bR"

[[key_bindings]]
key = "S"
mods = "Alt|Shift"
chars = "\u001bS"

[[key_bindings]]
key = "T"
mods = "Alt|Shift"
chars = "\u001bT"

[[key_bindings]]
key = "U"
mods = "Alt|Shift"
chars = "\u001bU"

[[key_bindings]]
key = "V"
mods = "Alt|Shift"
chars = "\u001bV"

[[key_bindings]]
key = "W"
mods = "Alt|Shift"
chars = "\u001bW"

[[key_bindings]]
key = "X"
mods = "Alt|Shift"
chars = "\u001bX"

[[key_bindings]]
key = "Y"
mods = "Alt|Shift"
chars = "\u001bY"

[[key_bindings]]
key = "Z"
mods = "Alt|Shift"
chars = "\u001bZ"

[[key_bindings]]
key = "Key1"
mods = "Alt"
chars = "\u001b1"

[[key_bindings]]
key = "Key2"
mods = "Alt"
chars = "\u001b2"

[[key_bindings]]
key = "Key3"
mods = "Alt"
chars = "\u001b3"

[[key_bindings]]
key = "Key4"
mods = "Alt"
chars = "\u001b4"

[[key_bindings]]
key = "Key5"
mods = "Alt"
chars = "\u001b5"

[[key_bindings]]
key = "Key6"
mods = "Alt"
chars = "\u001b6"

[[key_bindings]]
key = "Key7"
mods = "Alt"
chars = "\u001b7"

[[key_bindings]]
key = "Key8"
mods = "Alt"
chars = "\u001b8"

[[key_bindings]]
key = "Key9"
mods = "Alt"
chars = "\u001b9"

[[key_bindings]]
key = "Key0"
mods = "Alt"
chars = "\u001b0"

[[key_bindings]]
key = "Space"
mods = "Control"
chars = "\u0000"

[[key_bindings]]
key = "Grave"
mods = "Alt"
chars = "\u001b`"

[[key_bindings]]
key = "Grave"
mods = "Alt|Shift"
chars = "\u001b~"

[[key_bindings]]
key = "Period"
mods = "Alt"
chars = "\u001b."

[[key_bindings]]
key = "Key8"
mods = "Alt|Shift"
chars = "\u001b*"

[[key_bindings]]
key = "Key3"
mods = "Alt|Shift"
chars = "\u001b#"

[[key_bindings]]
key = "Period"
mods = "Alt|Shift"
chars = "\u001b>"

[[key_bindings]]
key = "Comma"
mods = "Alt|Shift"
chars = "\u001b<"

[[key_bindings]]
key = "Minus"
mods = "Alt|Shift"
chars = "\u001b_"

[[key_bindings]]
key = "Key5"
mods = "Alt|Shift"
chars = "\u001b%"

[[key_bindings]]
key = "Key6"
mods = "Alt|Shift"
chars = "\u001b^"

[[key_bindings]]
key = "Backslash"
mods = "Alt"
chars = "\u001b\\"

[[key_bindings]]
key = "Backslash"
mods = "Alt|Shift"
chars = "\u001b|"

[[key_bindings]]
key = "F1"
action = "None"
