format = """
$directory\
$git_branch\
$git_status\
$git_state\
$nodejs\
$python\
${custom.raftt}\
\n\
${env_var.SHELL_EMOTICON}\
$character
"""

right_format = """
$cmd_duration\
$status\
"""

[directory]
style = "bold cyan"
truncate_to_repo = true
format = "[](bold bright-blue)[$path ]($style)"
home_symbol = "~"

[git_branch]
style = "bold purple"
format = "[$branch ]($style)"

[custom.raftt]
command = "raftt-widget"
style = "bold cyan"
detect_folders = [".raftt"]
format = "[$symbol( $output )]($style)"
disabled = true

[status]
disabled = false
symbol = "🤦"

[cmd_duration]
min_time = 500
format = "\n[$duration](bold yellow)"

[env_var.SHELL_EMOTICON]
variable = "SHELL_EMOTICON"
style = "yellow"
format = "[$env_value ]($style)"

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

[nodejs]
format = "[🤖 $version](bold green)"
detect_extensions = []

[python]
symbol = '👾 '
pyenv_version_name = true
format = '[${symbol}$virtualenv]($style)'
