source $HOME/.envvars.rc
# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="erikzaadi"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git extract npm pip python vundle cake compleat django tmuxinator)
#fpath=($HOME/.tmuxinator/completion ${fpath})
#autoload -U compinit
#compinit

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/usr/local/sbin:$HOME/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/xpyv/bin:$APPSDIR/frameworks/android-sdk-linux/tools:$APPSDIR/frameworks/android-sdk-linux/platform-tools:$APPSDIR/frameworks/airsdk/bin:$APPSDIR/frameworks/android-ndk-r8
#export PYTHONSTARTUP=~/.pythonrc.py
export MAILPATH=/var/mail/$USER
export MAILCHECK=60
alias jenkins-cli="java -jar $APPSDIR/jenkinsCli/jenkins-cli.jar -s $JENKINS_URL"
eval `dircolors $OPENSOURCEDIR/other/utils/dircolors-solarized/dircolors.256dark`
#alias la='ls -lsa'
alias xclipc="xclip -selection c"
#alias lvds='xrandr --output VGA1 --off --output DP1 --off --output LVDS1 --1280x800 --primary'
#alias vga='xrandr --output DP1 --off --output VGA1 --auto --primary --output LVDS1 --mode 1280x800 --left-of VGA1'
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
export TERM=xterm-256color
export EDITOR=vim
# start tmux session hacking if the hacking session is not active/existing else just bare tmux
if [ "$TMUX" = "" ]; then
    # not if tmux session
    `tmux list-session | grep hacking > /dev/null`
    # check for hacking session
    if [ $? = 0 ]; then
        # tmux hacking found
        `tmux list-session | grep attached | grep hacking > /dev/null`
        if [ $? = 0 ]; then
            # hacking found active create a new session
            tmux -2 new
        else
            # hacking found but not active
            tmux -2 attach -t hacking
        fi
    else
        # hacking not found
        tmux -2 new -s hacking
    fi
fi
