source $HOME/.envvars.rc
autoload -U compinit
compinit
autoload -U bashcompinit
bashcompinit
source $OPENSOURCEDIR/other/utils/antigen/antigen.zsh
# Load the oh-my-zsh's library.
antigen use oh-my-zsh
# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen-bundles <<EOBUNDLES

git-flow
coffee
django
pip
gem
extract
ssh-agent
brew
bundler
colored-man
fabric
lol
git-extras
vagrant

aziz/tmuxinator completion

EOBUNDLES

# Load the theme.
#antigen-theme $OPENSOURCEDIR/mine/dotFiles/zsh/erikzaadi.zsh-theme
antigen-theme jonathan

# Tell antigen that you're done.
antigen-apply

export PATH=/usr/local/sbin:$HOME/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${JAVA_HOME}/bin:$HOME/.rvm/bin
export MAILPATH=/var/mail/$USER
alias pwdc='pwd | pbcopy'
alias chuck='sudo'
psgrep() {
    ps aux | grep $1 | egrep -v "grep"
}
psgrep-id() {
    ps aux | grep $1 | egrep -v "grep" | awk '{print $2;}'
}
#alias apt-search="aptitude search"
#alias apt-show="aptitude show"
#installed() {
#    apt-search $1 | grep "^i"
#}
alias git="hub"
alias gf='git flow'
export TERM=xterm-256color
#export TERM=screen-256color
export EDITOR=vim
# start tmux session hacking if the hacking session is not active/existing else just bare tmux
#if [ "$TMUX" = "" ]; then
#    # not if tmux session
#    `tmux list-session | grep hacking > /dev/null`
#    # check for hacking session
#    if [ $? = 0 ]; then
#        # tmux hacking found
#        `tmux list-session | grep attached | grep hacking > /dev/null`
#        if [ $? = 0 ]; then
#            # hacking found active create a new session
#            tmux -2 new
#        else
#            # hacking found but not active
#            hack
#        fi
#    else
#        # hacking not found
#        hack
#    fi
#fi

#if [ -f ~/.xmodmap ]; then
#    xmodmap ~/.xmodmap
#fi
autoload -U zmv
alias mmv='noglob zmv -W'
alias :q=exit #https://coderwall.com/p/fdtaia?&p=2&q=
delete-line()
{
    sed -i -e "$2d" $1
}

#_nosetests()
#{
#    cur="${COMP_WORDS[COMP_CWORD]}"
#    COMPREPLY=(`nosecomplete ${cur} 2>/dev/null`)
#}
#complete -o nospace -F _nosetests nosetests
[[ -s ~/.nvm/nvm.sh ]] && . ~/.nvm/nvm.sh && . ~/.nvm/bash_completion # This loads NVM
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
#cn  #commented out, productivity killerz
