source $HOME/.envvars.rc
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="erikzaadi"
plugins=(git github ant compleat yum extract npm node pip python vundle cake compleat django tmuxinator gem bundler battery rvm ssh-agent mvn rake)
source $ZSH/oh-my-zsh.sh
autoload -U edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line
#perhaps move this to envvars as it's rathed specific..
export PATH=/usr/local/sbin:$HOME/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/xpyv/bin:$APPSDIR/frameworks/android-sdk-linux/tools:$APPSDIR/frameworks/android-sdk-linux/platform-tools:$APPSDIR/frameworks/airsdk/bin:$APPSDIR/frameworks/android-ndk-r8:${JAVA_HOME}/bin:$HOME/.tmuxinator/scripts
#export PYTHONSTARTUP=~/.pythonrc.py
export MAILPATH=/var/mail/$USER
#export MAILCHECK=60
if [ -f $OPENSOURCEDIR/other/utils/solarized/dircolors-solarized/dircolors.256dark ]; then
    eval `dircolors $OPENSOURCEDIR/other/utils/solarized/dircolors-solarized/dircolors.256dark`
fi
#alias la='ls -lsa'
alias xclipc="xclip -selection c"
alias chuck='sudo'
#alias lvds='xrandr --output VGA1 --off --output DP1 --off --output LVDS1 --1280x800 --primary'
#alias vga='xrandr --output DP1 --off --output VGA1 --auto --primary --output LVDS1 --mode 1280x800 --left-of VGA1'
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
export TERM=xterm-256color
export EDITOR=vim
# start tmux session hacking if the hacking session is not active/existing else just bare tmux
if [ "$TMUX" = "" ]; then
    # not if tmux session
    `tmux list-session | grep hacking > /dev/null`
    # check for hacking session
    if [ $? = 0 ]; then
        # tmux hacking found
        `tmux list-session | grep attached | grep hacking > /dev/null`
        if [ $? = 0 ]; then
            # hacking found active create a new session
            tmux -2 new
        else
            # hacking found but not active
            hack
        fi
    else
        # hacking not found
        hack
    fi
fi

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
if [ -f ~/.xmodmap ]; then
    xmodmap ~/.xmodmap
fi
