#!/bin/bash
CURRENT_LANGUAGE=`apple-language`
SWEDEN="🇸🇪"
ISRAEL="🇮🇱"
US="🇺🇸"


case ${CURRENT_LANGUAGE} in
    ABC)
        echo ${US}
        ;;
    Swedish)
        echo ${SWEDEN}
        ;;
    'Swedish - Pro')
        echo ${SWEDEN}
        ;;
    Hebrew)
        echo ${ISRAEL}
        ;;
esac
