#!/usr/bin/env bash
which gcalcli > /dev/null
if [[ $? != 0 ]]; then
    echo ""
    exit 0
fi
CALENDAR=$(gcalcli list  | grep owner | awk '{print $3};' | tail -n 1)
NEXT_UP=$(
    # get agenda for next 20 minutes in tsv
    gcalcli agenda --calendar "${CALENDAR}" --tsv "$(date +"%H:%M")" "$(date -d "+ 25 Minutes" +"%H:%M")" --details 'title' | \
        jq -Rsj 'split("\n")[1:-1] |
         map([split("\t")[]|split(",")] | {
                 "start_date":.[0],
                 "start_time":.[1],
                 "end_date":.[2],
                 "end_time":.[3],
                 "title":.[4],
             })
             | .[] | select(.start_time | length > 0)
             | select(.start_time[0] < .end_time[0])
             | " \(.start_time[0])-\(.end_time[0]) \(.title[0][0:15])"'
    )

if [[ -z "${NEXT_UP}" ]]; then
    exit 0
fi

echo "[${NEXT_UP} ]"
