#!/bin/bash

WIFI_ON="📶 "
WIFI_OFF="🚫 "
WIFI_AVAILABLE="🔄 "

if [[ "$(uname)" == "Darwin" ]]; then
    RESULT=`/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I`
    if [[ "${RESULT}" = "AirPort: Off" ]]; then
        echo "${WIFI_OFF}"
        exit 0
    fi
    SSID=`echo "${RESULT}" | grep "SSID:" | tail -n 1 | awk '{print $2};'`
    if [[ "${SSID}" = "" ]]; then
        echo "${WIFI_AVAILABLE}"
    else
        SIGNAL_STRENGTH=`echo "${RESULT}" | grep "agrCtlRSSI:" | awk '{print $2};'`

        if [[ ${SIGNAL_STRENGTH} -gt -51 ]]; then
            PERCENT=100
        else
            PERCENT=$(( 2 * (100 + ${SIGNAL_STRENGTH}) ))""
        fi
        echo "${WIFI_ON}${SSID}:${PERCENT}%"
    fi
else
    echo "${WIFI_ON}$(awk 'NR==3 {print \"\" (\$3/70)*100 \"%\"}' /proc/net/wireless)"
fi
