#all ze completions
fpath=(/usr/local/share/zsh-completions $fpath)
fpath=(${DOTFILESDIR}/zsh/completions $fpath)

# zsh > bash
autoload -U compinit
compinit
autoload -U bashcompinit
bashcompinit

# Paths
export MAILPATH=/var/mail/$USER

[[ -s ~/.nvm/nvm.sh ]] && . ~/.nvm/nvm.sh && . ~/.nvm/bash_completion # This loads NVM

source $HOME/.zshenv

source <(antibody init)

antibody bundle < $DOTFILESDIR/zsh/plugins

source $DOTFILESDIR/zsh/defaults

## Load my theme.
source ${DOTFILESDIR}/zsh/erikzaadi.zsh-theme

alias chuck='sudo'
alias git-last="git log -1 | g_or_native tail -1 | g_or_native awk '{print $1}'"
alias pwdc='pwd | ${CLIPBOARD}'

psgrep() {
    ps aux | g_or_native grep $1 | egrep -v "grep"
}
psgrep-id() {
    ps aux | g_or_native grep $1 | egrep -v "grep" | g_or_native awk '{print $2;}'
}
delete-line()
{
    g_or_native sed -i -e "$2d" $1
}

alias gf='git flow'
alias ms="tmuxp load"
export TERM=xterm-256color
export EDITOR=vim
autoload -U zmv
alias mmv='noglob zmv -W'
alias :q=exit #https://coderwall.com/p/fdtaia?&p=2&q=
alias :e=vim
alias edit=vim
alias e=vim
alias delete-known-host-list="delete-line ~/.ssh/known_hosts"

alias ls="g_or_native ls --color"
eval `dircolors ${DOTFILESDIR}/deps/dircolors-solarized/dircolors.256dark`
#
# Solarized FZF
export FZF_DEFAULT_OPTS='
  --bind ctrl-f:page-down,ctrl-b:page-up
  --color dark,hl:33,hl+:37,fg+:235,bg+:136,fg+:254
  --color info:254,prompt:37,spinner:108,pointer:235,marker:235
'
